# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 411)
        MainWindow.setMinimumSize(QtCore.QSize(800, 411))
        MainWindow.setMaximumSize(QtCore.QSize(800, 411))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/robot-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblUsuario = QtWidgets.QLabel(self.centralwidget)
        self.lblUsuario.setGeometry(QtCore.QRect(210, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblUsuario.setFont(font)
        self.lblUsuario.setObjectName("lblUsuario")
        self.lblContrasena = QtWidgets.QLabel(self.centralwidget)
        self.lblContrasena.setGeometry(QtCore.QRect(190, 170, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblContrasena.setFont(font)
        self.lblContrasena.setObjectName("lblContrasena")
        self.txtUsuario = QtWidgets.QLineEdit(self.centralwidget)
        self.txtUsuario.setGeometry(QtCore.QRect(350, 80, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtUsuario.setFont(font)
        self.txtUsuario.setObjectName("txtUsuario")
        self.txtContrasena = QtWidgets.QLineEdit(self.centralwidget)
        self.txtContrasena.setGeometry(QtCore.QRect(350, 170, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtContrasena.setFont(font)
        self.txtContrasena.setObjectName("txtContrasena")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(190, 250, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnCancelar.setFont(font)
        self.btnCancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/cacelar.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancelar.setIcon(icon1)
        self.btnCancelar.setObjectName("btnCancelar")
        self.btnAceptar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAceptar.setGeometry(QtCore.QRect(390, 250, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnAceptar.setFont(font)
        self.btnAceptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/icon-Aceptar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAceptar.setIcon(icon2)
        self.btnAceptar.setObjectName("btnAceptar")
        self.img_logo = QtWidgets.QLabel(self.centralwidget)
        self.img_logo.setGeometry(QtCore.QRect(590, 80, 161, 181))
        self.img_logo.setText("")
        self.img_logo.setPixmap(QtGui.QPixmap("img/logo-Candado.png"))
        self.img_logo.setScaledContents(True)
        self.img_logo.setObjectName("img_logo")
        self.lblMensaje = QtWidgets.QLabel(self.centralwidget)
        self.lblMensaje.setGeometry(QtCore.QRect(250, 330, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblMensaje.setFont(font)
        self.lblMensaje.setObjectName("lblMensaje")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema de encriptacion de archivos"))
        self.lblUsuario.setText(_translate("MainWindow", "Usuario:"))
        self.lblContrasena.setText(_translate("MainWindow", "Contrasena:"))
        self.btnCancelar.setText(_translate("MainWindow", "Cancelar"))
        self.btnAceptar.setText(_translate("MainWindow", "Entrar"))
        self.lblMensaje.setText(_translate("MainWindow", "Mensaje de Autentificación"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
